const SESSION_AUTH = "cookies"


const BRANCH_ID = "branch_id"

const CALL = "call"

const EMPLOYEE_SPECIALIST = "Especialista"
const EMPLOYEE_MEDICAL = "Medico"



const EMPTY_PAYMENT_METHOD = 'EMPTY_PAYMENT_METHOD';
const EMPTY_COST = 'EMPTY_COST';
const EMPTY_SERVICE = 'EMPTY_SERVICE'
const EXISTING_SERVICE = "EXISTING_SERVICE"
const EMPTY_TIMES = "EMPTY_TIMES"
const PATIENT_PAD_EXISTS = 'PATIENT_PAD_EXISTS'
const IS_INDIVIDUAL_PAD = "IS_INDIVIDUAL_PAD"
const MAX_MEMBERS_PAD = "MAX_MEMBERS_PAD"
const EXISTING_PAYMENT_METHOD = "EXISTING_PAYMENT_METHOD"
const EMPTY_AMOUNT = "EMPTY_AMOUNT"


const STATUS_ACTIVE = 'active'
const STATUS_PROCESS = 'process'
const STATUS_INACTIVE = 'inactive'
const STATUS_FINISHED = 'finished'
const STATUS_NOT_ATTENDED = 'not-attended'
const STATUS_CANCELLED = 'cancelled'
const STATUS_FINISHED_APPOINTMENT_OR_CALL = 'finished-appointment-or-call'
const STATUS_SOLVED = 'solved'
const STATUS_ABANDOMENT = 'abandonment'
const STATUS_MANUAL = 'manual'
const STATUS_AUTOMATIC = 'automatic'
const STATUS_DISBALED = 'disabled'
const DIFFERENT_PASSWORD = "DIFFERENT_PASSWORD"
const MIN_LENGTH = "MIN_LENGTH"

const ALREADY_EXIST_SERVICE = "ALREADY_EXIST_SERVICE"
const ALREADY_EXIST_SERVICE_PAD = "ALREADY_EXIST_SERVICE_PAD"

const DEBT_ACTIVE = "DEBT_ACTIVE"

const PAYMENT_DEBT_ACTIVE = "PAYMENT_DEBT_ACTIVE"
const REQUIRED_FIELDS = 'REQUIRED_FIELDS'
const ERROR_ADDING_PAD_COMPONENT = "ERROR_ADDING_PAD_COMPONENT"


export default {
    STATUS_DISBALED,
    STATUS_MANUAL,
    STATUS_AUTOMATIC,
    STATUS_ABANDOMENT,
    STATUS_SOLVED,
    STATUS_FINISHED_APPOINTMENT_OR_CALL,
    STATUS_CANCELLED,
    STATUS_NOT_ATTENDED,
    STATUS_FINISHED,
    STATUS_INACTIVE,
    STATUS_PROCESS,
    STATUS_ACTIVE,
    SESSION_AUTH,
    BRANCH_ID,
    EMPLOYEE_SPECIALIST,
    EMPLOYEE_MEDICAL,
    CALL,
    EMPTY_COST,
    EMPTY_PAYMENT_METHOD,
    EMPTY_SERVICE,
    EXISTING_SERVICE,
    EMPTY_TIMES,
    PATIENT_PAD_EXISTS,
    IS_INDIVIDUAL_PAD,
    MAX_MEMBERS_PAD,
    EXISTING_PAYMENT_METHOD,
    EMPTY_AMOUNT,
    DIFFERENT_PASSWORD,
    MIN_LENGTH,
    ALREADY_EXIST_SERVICE,
    ALREADY_EXIST_SERVICE_PAD, DEBT_ACTIVE,
    PAYMENT_DEBT_ACTIVE,
    REQUIRED_FIELDS,
    ERROR_ADDING_PAD_COMPONENT

}