const SESSION_AUTH = "cookies"


const BRANCH_ID = "branch_id"

const CALL = "call"

const EMPLOYEE_SPECIALIST = "Especialista"
const EMPLOYEE_MEDICAL = "Medico"



const EMPTY_PAYMENT_METHOD = 'EMPTY_PAYMENT_METHOD';
const EMPTY_COST = 'EMPTY_COST';
const EMPTY_SERVICE = 'EMPTY_SERVICE'

export default {
    SESSION_AUTH,
    BRANCH_ID,
    EMPLOYEE_SPECIALIST,
    EMPLOYEE_MEDICAL,
    CALL,
    EMPTY_COST,
    EMPTY_PAYMENT_METHOD,
    EMPTY_SERVICE
}