const SESSION_AUTH = "cookies"


const BRANCH_ID = "branch_id"

const CALL = "call"

const EMPLOYEE_SPECIALIST = "Especialista"
const EMPLOYEE_MEDICAL = "Medico"



const EMPTY_PAYMENT_METHOD = 'EMPTY_PAYMENT_METHOD';
const EMPTY_COST = 'EMPTY_COST';
const EMPTY_SERVICE = 'EMPTY_SERVICE'
const EXISTING_SERVICE = "EXISTING_SERVICE"
const EMPTY_TIMES = "EMPTY_TIMES"
const PATIENT_PAD_EXISTS = 'PATIENT_PAD_EXISTS'
const IS_INDIVIDUAL_PAD = "IS_INDIVIDUAL_PAD"
const MAX_MEMBERS_PAD = "MAX_MEMBERS_PAD"
export default {
    SESSION_AUTH,
    BRANCH_ID,
    EMPLOYEE_SPECIALIST,
    EMPLOYEE_MEDICAL,
    CALL,
    EMPTY_COST,
    EMPTY_PAYMENT_METHOD,
    EMPTY_SERVICE,
    EXISTING_SERVICE,
    EMPTY_TIMES,
    PATIENT_PAD_EXISTS,
    IS_INDIVIDUAL_PAD,
    MAX_MEMBERS_PAD
}