name: Firebase Deployment - Develop
on:
  push:
    branches:
      - develop
jobs:
  build:
        name: Build
        runs-on: ubuntu-latest
        steps:
          - name: Checkout Repo
            uses: actions/checkout@v3
          - name: Install Dependencies
            run: npm install
          - name: 'Update env file for DEV'
            run: |
              echo VITE_URL_SERVICE=${{ secrets.DEV_URL_SERVICE }} >> .env.development
              echo VITE_APP_VERSION=${{ secrets.APP_VERSION }} >> .env.development
              echo VITE_ENV_NAME=${{ secrets.DEV_ENV_NAME }} >> .env.development
              cat .env.development
          - name: Build
            run: npm run build:dev
          - name: Archive Production Artifact
            uses: actions/upload-artifact@v3
            with:
              name: dist
              path: dist
  deploy:
        name: Deploy
        needs: build
        runs-on: ubuntu-latest
        steps:
          - name: Checkout Repo
            uses: actions/checkout@v3
          - name: Download Artifact
            uses: actions/download-artifact@v3
            with:
              name: dist
              path: dist
          - name: Deploy to Firebase Development
            uses: w9jds/firebase-action@master
            with:
              args: deploy -P development
            env:
              FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
